spring:
  application:
    name: projectHub
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projecthub}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-verification-key: ${JWT_PUBLIC_KEY}
      authorizationserver:
        jwt:
          jws-signing-key: ${JWT_PRIVATE_KEY}